// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifqsauluskawtdanthpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmcXNhdWx1c2thd3RkYW50aHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjQ3NzUsImV4cCI6MjA2OTQ0MDc3NX0.t1SzZ17yQhwwLRsajRrZr_BhtFkaKSJ6sUc2uZIQPPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});